
import React, {useState} from "react";
import {SafeAreaView,View,Text,TextInput,Pressable,Image,ScrollView,StyleSheet,StatusBar} from "react-native";

const Y="#FFDD63", BG="#F7F3E7", INK="#111827", MUTED="#77736A", ORANGE="#FFC766", WHITE="#FFF";
const A={
 logo:require("./assets/logo.jpg"), globe:require("./assets/globe.jpg"), profile:require("./assets/profile.jpg"),
 forest:require("./assets/forest.jpg"), boardgame:require("./assets/boardgame.jpg"),
 mountain:require("./assets/mountain.jpg"), dinner:require("./assets/dinner.jpg")
};

const people=[
 ["Sophia Martinez","@sophmart","Hiking","Photography","Cooking"],
 ["Julian Vance","@julianv","Music","Art","Gaming"],
 ["Emma Watson","@emmaw","Food","Hiking","Music"]
];

function Logo({small=false}){return <Image source={A.logo} resizeMode="contain" style={{width:small?82:185,height:small?38:72}}/>}
function Button({children,onPress,light=false}){return <Pressable onPress={onPress} style={[s.button,light&&s.light]}><Text style={[s.buttonText,light&&{color:INK}]}>{children}</Text></Pressable>}
function Field({placeholder}){return <TextInput placeholder={placeholder} placeholderTextColor="#777" style={s.field}/>}
function BottomNav({tab,go}){return <View style={s.bottom}>{[["Home","home","⌂"],["Events","events","▣"],["Friends","friends","♙"],["Settings","settings","⚙"]].map(([l,k,i])=><Pressable key={k} onPress={()=>go(k)} style={s.nav}><Text style={s.navIcon}>{i}</Text><Text style={[s.navText,tab===k&&{fontWeight:"900"}]}>{l}</Text></Pressable>)}</View>}

function Auth({children}){return <SafeAreaView style={s.yellow}><ScrollView contentContainerStyle={s.auth}>{children}</ScrollView></SafeAreaView>}
function Splash({go}){return <Auth><Logo/><Text style={s.tagline}>Find your third place.</Text><Image source={A.globe} style={s.globe}/><Button onPress={()=>go("login")}>Log in</Button><Button light onPress={()=>go("create")}>Create Account</Button></Auth>}
function Login({go}){return <Auth><Logo/><Text style={s.authTitle}>Welcome Back!</Text><Field placeholder="♙   Username"/><Field placeholder="▢   Password"/><Button onPress={()=>go("home")}>Sign In</Button><Button light onPress={()=>go("splash")}>Back</Button></Auth>}
function Create({go}){return <Auth><Logo/><Field placeholder="♙   Username"/><Field placeholder="▢   Password"/><Field placeholder="▢   Confirm password"/><Button onPress={()=>go("interests")}>Create Account</Button><Button light onPress={()=>go("splash")}>Back</Button></Auth>}
function Interests({go}){const tags=["Anime","Art","Books","Dance","Video Games","Movies","Party","Gym","Music","Fishing","Food","Hiking"];const [sel,setSel]=useState(["Art","Music"]);return <Auth><Logo small/><Text style={s.smile}>⌒   ⌒</Text><Text style={s.center}>Choose your interests</Text><View style={s.tags}>{tags.map(t=><Pressable key={t} onPress={()=>setSel(x=>x.includes(t)?x.filter(y=>y!==t):[...x,t])} style={[s.tag,sel.includes(t)&&s.tagSelected]}><Text style={s.tagText}>{t}</Text></Pressable>)}</View><Text style={s.smile}>⌣</Text><Button onPress={()=>go("profile")}>Continue</Button></Auth>}
function Profile({go}){return <Auth><Logo small/><Text style={s.center}>Finish your profile!</Text><Image source={A.profile} style={s.avatarLarge}/><Button>Take Photo</Button><View style={s.tags}>{["Dance","Art","Hiking","Party","Music","Food","Video Games"].map(t=><View key={t} style={s.tag}><Text style={s.tagText}>{t}</Text></View>)}</View><Field placeholder="Name:          Real Person"/><Field placeholder="Age:                 20"/><Button onPress={()=>go("home")}>Continue</Button></Auth>}

function Header({title,subtitle}){return <View><Text style={s.h1}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>}
function Card({title,children}){return <View style={s.card}>{title&&<Text style={s.cardTitle}>{title}</Text>}{children}</View>}
function Toggle({label,on}){return <View style={s.rowBetween}><Text style={s.body}>{label}</Text><View style={[s.toggle,on&&s.toggleOn]}><View style={[s.toggleDot,on&&{marginLeft:18}]}/></View></View>}
function EventMini({title,meta,image}){return <View style={s.eventMini}><Image source={image} style={s.eventThumb}/><View style={{flex:1}}><Text style={s.cardTitle}>{title}</Text><Text style={s.small}>{meta}</Text><Text style={s.small}>⌖ Local meetup • 0.4 mi</Text></View></View>}

function Home({go}){return <SafeAreaView style={s.screen}><View style={s.mapHeader}><Text style={s.menu}>☰</Text><Logo small/><Text>🔔</Text></View><View style={{padding:10}}><Field placeholder="⌕  Search activities, coffee, parks..."/></View><View style={s.map}><Text style={s.mapRoad}>┼ ┼ ┼ ┼</Text><Text style={s.mapPin}>📍</Text><Text style={[s.mapPin,{right:35,top:90}]}>📍</Text></View><ScrollView style={{padding:10}}><View style={s.sectionRow}><Text style={s.sectionTitle}>Events Nearby</Text><Text style={s.small}>See All</Text></View>{[["Board Game Club Weekly Meetup","Tonight, 7:00 PM",A.boardgame],["Yoga Meetup","Saturday, 5:30 PM",A.mountain],["Jazz Club - Live Afrobeat Jazz Show","Sunday, 4:00 PM",A.dinner]].map(x=><EventMini key={x[0]} title={x[0]} meta={x[1]} image={x[2]}/>)}</ScrollView><BottomNav tab="home" go={go}/></SafeAreaView>}

function Settings({go}){return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><Header title="App Settings" subtitle="Personalize your Together! account and notification privacy."/><Card title="Account Settings"><View style={s.row}><Image source={A.profile} style={s.avatar}/><Button light>Change Photo</Button><Button light>Remove</Button></View><Field placeholder="Display Name     Milo Parker"/><Field placeholder="Username          @milopark"/><Field placeholder="Email Address     milo.parker@example.com"/></Card><Card title="Appearance"><Toggle label="Enable Dark Theme"/><Toggle label="Compact List Layout" on/></Card></ScrollView><BottomNav tab="settings" go={go}/></SafeAreaView>}

function Friends({go,friends=false}){return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><View style={s.profileStrip}><Image source={A.profile} style={s.avatar}/><View><Text style={s.cardTitle}>Real Person</Text><Text style={s.small}>@milopark</Text></View></View><Header title="My Social Circle" subtitle="Coordinate with 24 friends around your local neighborhood."/><Field placeholder="⌕  Search friends..."/><View style={s.segment}><Text>Discover</Text><Text>My Groups</Text><Text style={friends&&s.segmentActive}>Friends</Text></View>{!friends&&<><Text style={s.sectionTitle}>Discover by Hobby</Text><View style={s.tags}>{["Hiking","Photography","Cooking","Music"].map(t=><View key={t} style={s.tag}><Text style={s.tagText}>{t}</Text></View>)}</View><Text style={s.sectionTitle}>People You Might Know</Text></>}{people.map(p=><View key={p[0]} style={s.personCard}><Image source={A.profile} style={s.avatar}/><View style={{flex:1}}><Text style={s.cardTitle}>{p[0]}</Text><Text style={s.small}>{p[1]}</Text><View style={s.tags}>{p.slice(2).map(x=><View key={x} style={s.tag}><Text style={s.tagText}>{x}</Text></View>)}</View><Text style={s.small}>3 shared hobbies</Text></View><Button light>{friends?"Message":"Add Friend"}</Button></View>)}</ScrollView><BottomNav tab="friends" go={go}/></SafeAreaView>}

function Groups({go,detail=false}){if(detail)return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><Text style={s.cardTitle}>‹  Weekend Hikers</Text><Image source={A.forest} style={s.hero}/><Header title="Weekend Hikers" subtitle="8 members • Active Group"/><Text style={s.sectionTitle}>Members (8)</Text>{people.map(p=><View style={s.member} key={p[0]}><Image source={A.profile} style={s.avatar}/><Text>{p[0]}</Text></View>)}<Card title="Upcoming Events"><EventMini title="Stone Mountain Sunrise Hike" meta="Sat, Oct 14 • 8:00 AM" image={A.mountain}/></Card></ScrollView><BottomNav tab="friends" go={go}/></SafeAreaView>;return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><View style={s.profileStrip}><Image source={A.profile} style={s.avatar}/><View><Text style={s.cardTitle}>Real Person</Text><Text style={s.small}>@milopark</Text></View></View><Header title="My Social Circle" subtitle="Coordinate with 24 friends around your local neighborhood."/><View style={s.segment}><Text>Discover</Text><Text style={s.segmentActive}>My Groups</Text><Text>Friends</Text></View><Button light onPress={()=>go("createGroup")}>Create New Group</Button>{["Weekend Hikers","Photography Club","Board Game Night"].map(g=><Card title={g} key={g}><Text style={s.body}>Exploring scenic trails, social viewpoints, and cozy gatherings with local friends.</Text><Button light onPress={()=>go("groupDetail")}>View</Button></Card>)}</ScrollView><BottomNav tab="friends" go={go}/></SafeAreaView>}

function CreateGroup({go}){return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><Text style={s.cardTitle}>‹  Create Group</Text><Text style={s.label}>Group Name</Text><Field placeholder="e.g. Sunday Brunch Club"/><Text style={s.label}>Description</Text><Field placeholder="What is your cozy group all about?"/><Text style={s.label}>Select Hobby Category</Text><View style={s.tags}>{["Hiking","Photography","Cooking","Music","Art","Gaming"].map(t=><View style={s.tag} key={t}><Text style={s.tagText}>{t}</Text></View>)}</View><Text style={s.label}>Add Members</Text>{people.map(p=><View style={s.member} key={p[0]}><Image source={A.profile} style={s.avatar}/><Text style={{flex:1}}>{p[0]}</Text><Text>Add</Text></View>)}<Toggle label="Private Group" on/><Button onPress={()=>go("groupDetail")}>Create Group</Button></ScrollView><BottomNav tab="friends" go={go}/></SafeAreaView>}

const allEvents=[["Weekend Hiking Trip","Sat, Oct 14 • 8:00 AM","Stone Mountain Reserve",A.forest],["Board Game Night","Fri, Oct 20 • 7:00 PM","Local Game Cafe",A.boardgame]];
function Events({go,mode="all"}){const data=mode==="past"?[[ "Birthday Bash at Milo's","Fri, Sep 29 • 6:30 PM","Milo's Rooftop Patio",A.dinner],["Sunday Morning Yoga","Sun, Sep 24 • 9:00 AM","Local Park",A.mountain]]:allEvents;return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><View style={s.rowBetween}><Header title="My Events" subtitle="Browse, coordinate, and review your community meetups."/><Button onPress={()=>go("createEvent")}>＋ Create Event</Button></View><View style={s.segment}><Text>All</Text><Text style={mode==="upcoming"&&s.segmentActive}>Upcoming</Text><Text style={mode==="past"&&s.segmentActive}>Past</Text></View>{data.map(x=><View key={x[0]} style={s.bigEvent}><Image source={x[3]} style={s.bigImage}/><View style={{padding:10}}><Text style={s.cardTitle}>{x[0]}</Text><Text style={s.small}>◷ {x[1]}</Text><Text style={s.small}>⌖ {x[2]}</Text><View style={s.rowBetween}><Text>👤👤👤</Text><Button light>{mode==="past"?"View Recap":"Manage"}</Button></View></View></View>)}</ScrollView><BottomNav tab="events" go={go}/></SafeAreaView>}

function CreateEvent({go}){return <SafeAreaView style={s.screen}><ScrollView contentContainerStyle={{padding:14,paddingBottom:70}}><Text style={s.cardTitle}>‹  Create Event</Text>{["Event Name","Date & Time","Location","Description"].map((x,i)=><View key={x}><Text style={s.label}>{x}</Text><Field placeholder={i===0?"e.g. Cozy Pizza & Board Games":i===1?"▣ Select date and time":i===2?"⌖ Enter venue or address":"Describe what makes this meetup special..."}/></View>)}<Text style={s.label}>Cover Photo</Text><View style={s.upload}><Text>▧</Text><Text>Tap to upload event banner</Text></View><Text style={s.label}>Hobby Tags</Text><View style={s.tags}>{["Board Games","Coffee","Music","Hiking","Art"].map(t=><View key={t} style={s.tag}><Text style={s.tagText}>{t}</Text></View>)}</View><Button onPress={()=>go("events")}>Create Event</Button></ScrollView><BottomNav tab="events" go={go}/></SafeAreaView>}

function App(){const [screen,setScreen]=useState("splash");const go=setScreen;if(screen==="splash")return <Splash go={go}/>;if(screen==="login")return <Login go={go}/>;if(screen==="create")return <Create go={go}/>;if(screen==="interests")return <Interests go={go}/>;if(screen==="profile")return <Profile go={go}/>;if(screen==="home")return <Home go={go}/>;if(screen==="settings")return <Settings go={go}/>;if(screen==="friends")return <Friends go={go}/>;if(screen==="friendList")return <Friends go={go} friends/>;if(screen==="groups")return <Groups go={go}/>;if(screen==="createGroup")return <CreateGroup go={go}/>;if(screen==="groupDetail")return <Groups go={go} detail/>;if(screen==="events")return <Events go={go}/>;if(screen==="upcoming")return <Events go={go} mode="upcoming"/>;if(screen==="past")return <Events go={go} mode="past"/>;if(screen==="createEvent")return <CreateEvent go={go}/>;return <Splash go={go}/>}

const s=StyleSheet.create({
 yellow:{flex:1,backgroundColor:Y},auth:{minHeight:874,padding:16,justifyContent:"center",alignItems:"center",gap:9},
 tagline:{fontSize:13,fontWeight:"700",marginTop:-8},globe:{width:185,height:185,marginVertical:5},authTitle:{fontSize:21,fontWeight:"900",color:"#6E6240",marginVertical:12},
 field:{height:39,backgroundColor:WHITE,borderRadius:20,paddingHorizontal:13,fontSize:11,marginVertical:4,width:"100%",borderWidth:1,borderColor:"#EEE9DC"},
 button:{backgroundColor:ORANGE,borderRadius:20,minHeight:40,paddingHorizontal:18,alignItems:"center",justifyContent:"center",marginVertical:4,width:"100%"},light:{backgroundColor:WHITE},buttonText:{fontSize:11,fontWeight:"800",color:WHITE},
 center:{fontSize:13,fontWeight:"900",marginVertical:5},smile:{fontSize:48,height:48,overflow:"hidden"},tags:{flexDirection:"row",flexWrap:"wrap",gap:5,justifyContent:"center",marginVertical:5},
 tag:{backgroundColor:"#FFC966",borderRadius:12,paddingHorizontal:9,paddingVertical:4},tagSelected:{backgroundColor:"#FFF0A7",borderWidth:1,borderColor:"#111"},tagText:{fontSize:9,fontWeight:"800"},
 avatarLarge:{width:95,height:95,borderRadius:48,borderWidth:7,borderColor:"#B8A86C",marginVertical:5},
 screen:{flex:1,backgroundColor:BG},mapHeader:{height:52,backgroundColor:Y,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:12},menu:{fontSize:22},
 map:{height:250,backgroundColor:"#FFF3B8",marginHorizontal:10,borderRadius:5,overflow:"hidden",position:"relative"},mapRoad:{fontSize:95,color:"#E6C65A",textAlign:"center",marginTop:50},mapPin:{position:"absolute",left:60,top:80,fontSize:24},
 sectionRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginVertical:8},sectionTitle:{fontSize:14,fontWeight:"900",color:INK,marginVertical:7},small:{fontSize:8,color:MUTED,marginTop:2},
 eventMini:{backgroundColor:WHITE,borderRadius:13,padding:7,marginVertical:4,flexDirection:"row",gap:8,borderWidth:1,borderColor:"#E6E1D5"},eventThumb:{width:34,height:34,borderRadius:17},
 bottom:{position:"absolute",left:0,right:0,bottom:0,height:48,backgroundColor:WHITE,borderTopWidth:1,borderTopColor:"#DDD8CC",flexDirection:"row",justifyContent:"space-around",alignItems:"center"},nav:{alignItems:"center",minWidth:60},navIcon:{fontSize:15},navText:{fontSize:7,color:INK},
 h1:{fontSize:22,fontWeight:"900",color:INK},subtitle:{fontSize:9,color:MUTED,lineHeight:13},profileStrip:{backgroundColor:"#FBF8EE",borderRadius:12,padding:9,flexDirection:"row",alignItems:"center",gap:8,marginBottom:10},
 avatar:{width:32,height:32,borderRadius:16},card:{backgroundColor:WHITE,borderRadius:13,padding:10,marginVertical:6,borderWidth:1,borderColor:"#E8E3D8"},cardTitle:{fontSize:11,fontWeight:"900",color:INK},
 row:{flexDirection:"row",alignItems:"center",gap:6},rowBetween:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},body:{fontSize:10,color:INK,lineHeight:15},
 toggle:{width:35,height:18,borderRadius:10,backgroundColor:"#E6E8EB",padding:2},toggleOn:{backgroundColor:"#F2AD37"},toggleDot:{width:14,height:14,borderRadius:7,backgroundColor:WHITE},
 segment:{backgroundColor:"#EDE9DE",borderRadius:18,padding:5,flexDirection:"row",justifyContent:"space-around",alignItems:"center",marginVertical:8},segmentActive:{backgroundColor:"#FFC45B",paddingHorizontal:12,paddingVertical:5,borderRadius:14,fontWeight:"900"},
 personCard:{backgroundColor:WHITE,borderRadius:13,padding:8,marginVertical:5,flexDirection:"row",gap:7,alignItems:"center"},member:{backgroundColor:WHITE,borderRadius:9,padding:7,marginVertical:3,flexDirection:"row",alignItems:"center",gap:8},label:{fontSize:9,fontWeight:"900",marginTop:8},
 hero:{width:"100%",height:130,borderRadius:12,marginVertical:8},bigEvent:{backgroundColor:WHITE,borderRadius:13,overflow:"hidden",marginVertical:6,borderWidth:1,borderColor:"#E8E3D8"},bigImage:{width:"100%",height:112},
 upload:{height:85,borderWidth:1,borderStyle:"dashed",borderColor:"#AAA",borderRadius:12,alignItems:"center",justifyContent:"center",gap:5,marginVertical:4}
});

function Root(){return <><StatusBar barStyle="dark-content"/><App/></>}
export default Root;
